% ---
%    Initialize the Multivariate Periodic Anisotropic Wavelet Library
%    by adding all needed folders relative to this file, where
%    the neccessary files reside.
% ---
% MPAWL 1.0 1.0 ~ R. Bergmann ~ 2014-12-13

folder = fileparts(which(mfilename));
% Add all necessary paths
addpath(...
    fullfile(folder, 'basic'),...
    fullfile(folder, 'debug'),...
    fullfile(folder, 'delaValleePoussin'),...
    fullfile(folder, 'helpers'),...
    fullfile(folder, 'pattern'),...
    fullfile(folder, 'sampling'),...
    fullfile(folder, 'spaces'),...
    fullfile(folder, 'test cases'),...
    fullfile(folder, 'transforms'),...
    fullfile(folder, 'validations'),...
    fullfile(folder, 'visualisations'),...
    genpath(fullfile(folder, 'tutorials'))...
);
% Init Debug
setDebugLevel(2);
debug('Text',3,'Text','Multivariate Periodic Anisotropic Wavelet Library.');
cd(getMPAWLPath());
%


